// <auto-generated />
using API_Vendas.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API_Vendas.Migrations
{
    [DbContext(typeof(_DbContext))]
    [Migration("20220725172201_FirstMigration")]
    partial class FirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("API_Vendas.Models.EstoqueProdutos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<int>("Qtde_estoque")
                        .HasColumnType("int");

                    b.Property<double>("Valor_unitario")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("Estoque");
                });
#pragma warning restore 612, 618
        }
    }
}
